[tool.poetry]
name = "mcd"
version = "0.1.0"
description = ""
authors = ["dag7dev <dag7@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
ndspy = "^4.1.0"

[tool.poetry.dev-dependencies]
